# docker-compose.yml
version: '3'
services:
  # PostgreSQL service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Nest.js application service
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/books
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network

# Define a custom network for the services to communicate
networks:
  app-network:
    driver: bridge

